services:
  database:
    image: postgres
    restart: always
    container_name: srvsupDB
    environment:
      POSTGRES_PASSWORD: KALIX
      POSTGRES_DB: srvsupDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./back
    restart: always
    container_name: srvsupBack
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:KALIX@database:5432/srvsupDB
    depends_on:
      - database

  frontend:
    build: ./front
    restart: always
    container_name: srvsupFront
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: 